name: open PR
author: Wanderlucio P Silva
description: This action open a pull request for a specified branch

inputs:
  branch:
    description: the branch which will receive de PR
    required: true

runs:
  using: composite
  shell: bash
  steps:
    - run: gh --version
    - run: gh auth refresh -s wandpsilva/open-pr
    - run: gh pr create --head teste --base main --fill 


branding:
  icon: 'cpu'
  color: 'green'