name: Run

on: workflow_dispatch

jobs:
  Run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: execute
        uses: ./